name: informatica_m_demo_mapping2
version: "1.0.0"
config-version: 2

profile: informatica_m_demo_mapping2

vars:
  m2_seq_current_value: 57
  business_date: "2024-01-31"

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
target-path: target
clean-targets:
  - target
  - dbt_packages

models:
  informatica_m_demo_mapping2:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table

seeds:
  informatica_m_demo_mapping2:
    demo_source1:
      +enabled: "{{ target.type == 'snowflake' }}"
      +column_types:
        LEAD_CO_MNE: varchar
        BRANCH_CO_MNE: varchar
        MIS_DATE: varchar
        ID: varchar
        DESCRIPTION: varchar
        SHORT_NAME: varchar
    demo_target1_pre:
      +enabled: "{{ target.type == 'snowflake' }}"
      +column_types:
        Key: double
        LEAD_CO_MNE: varchar
        BRANCH_CO_MNE: varchar
        MIS_DATE: varchar
        ID: varchar
        DESCRIPTION: varchar
        SHORT_NAME: varchar
        CREATED_BY: varchar
        CREATED_TIME: timestamp_ntz
        UPDATED_BY: varchar
        UPDATED_TIME: timestamp_ntz
        ACTIVE_FLAG: varchar
        START_DATE: timestamp_ntz
        END_DATE: timestamp_ntz
